language: ruby
rvm:
  - 2.3.0
sudo: false
cache: bundler
bundler_args: --without development
script:
  - git config --global user.name 'Tom Dooner'
  - git config --global user.email 'tomdooner@gmail.com'
  - bundle exec middleman build --verbose
  - bundle exec middleman deploy 2>&1 | sed -e "s/$GITHUB_AUTH_TOKEN//"
