language: ruby
rvm:
  - 2.2.2
sudo: false
cache: bundler
bundler_args: --without development
script:
  - bundle exec middleman build
  - bundle exec middleman deploy 2>&1 | sed -e "s/$GITHUB_AUTH_TOKEN//"
